// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   public static final class GameConstants {
      public static final int AUTO_TIME = 15;
      public static final int TELEOP_TIME = 135;
      public static final int ENDGAME_TIME = 30;
   }

   public static final class IntakeConstants {
      public static final int LIFT_MOTOR_ID = 0;
      public static final int LIFT_ENCODER_ID = 0;
      public static final double KP = 0;
      public static final double KI = 0;
      public static final double KD = 0;
      public static final double MAX_VEL = 0;
      public static final double MAX_ACC = 0;
      public static final double KS = 0;
      public static final double KG = 0;
      public static final double KV = 0;
      public static final double ENCODER_OFFSET = 0;
      public static final double CLOSED_POSITION = 0;
      public static final double OPENED_POSITION = 0;
      public static final double TOLERANCE = Math.PI / 20.0;

   }
}
