// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   public static final class GameConstants {
      public static final int AUTO_TIME = 15;
      public static final int TELEOP_TIME = 135;
      public static final int ENDGAME_TIME = 30;
   }

   public class DriveConstants {

      public static final int RIGHT_MASTER_ID = 1;
      public static final int RIGHT_SLAVE_ID = 2;
      public static final int LEFT_MASTER_ID = 3;
      public static final int LEFT_SLAVE_ID = 4;
      public static final int PIGEON_ID = 8;

      public static final double FWD_SPEED_FACTOR = 0.2;
      public static final double ROT_SPEED_FACTOR = 0.2;

      public static final double LP = 0;
      public static final double LI = 0;
      public static final double LD = 0;
      public static final double LKS = 0;
      public static final double LKV = 0;
      public static final double LKA = 0;

      public static final double RP = 0;
      public static final double RI = 0;
      public static final double RD = 0;
      public static final double RKS = 0;
      public static final double RKV = 0;
      public static final double RKA = 0;

   }

   public class GeneralConstants {
      public static final double DEFAULT_INPUT_DEADBAND = 0.02;
   }
}
